In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Cargo el DataSet del Titanic

In [2]:
df = sns.load_dataset('titanic',cache=True) # Carga el conjunto de datos 'titanic' utilizando la función load_dataset de la biblioteca seaborn y lo guarda en un DataFrame llamado df.
df.head() # Muestra las primeras filas del DataFrame df para obtener una vista previa de

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.info() # Proporciona información sobre el DataFrame df, incluyendo el número de filas, columnas, tipos de datos y cantidad de valores no nulos en cada columna.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [4]:
df.describe() # Genera estadísticas descriptivas para las columnas numéricas del DataFrame df, como la media, la desviación estándar, los valores mínimos y máximos, y los percentiles.

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

Búsqueda y tratamiento de datos faltantes (Nulos, NaN)

In [6]:
df['age'].value_counts(dropna=False) # Cuenta la frecuencia de cada valor único en la columna 'age' del DataFrame df y devuelve una serie con los valores únicos como índice y sus respectivas frecuencias como valores.

age
NaN      177
24.00     30
22.00     27
18.00     26
28.00     25
        ...
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: count, Length: 89, dtype: int64

In [7]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [8]:
df.notnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
887,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
888,True,True,True,False,True,True,True,True,True,True,True,False,True,True,True
889,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
890,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True

In [ ]:
df.isnull().sum() # Calcula la cantidad de valores nulos en cada columna del DataFrame df y devuelve una serie con los nombres de las columnas como índice y la cantidad de valores nulos como valores.

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [10]:
df.isnull().sum().sum() # Calcula la cantidad total de valores nulos en todo el DataFrame df sumando los valores obtenidos en el paso anterior. Devuelve un número entero que representa la cantidad total de valores nulos en el DataFrame.

869

In [11]:
# Eliminar las columnas que tengan más del 50% de valores nulos
threshold = int(len(df) * 0.5) # Calcula el umbral de valores no nulos necesarios para conservar una columna, que es el 50% del número total de filas en el DataFrame df. El resultado se almacena en la variable threshold.
nuevo_df = df.dropna(thresh=threshold, axis=1) # Elimina las columnas del DataFrame df que tengan más del 50% de valores nulos y guarda el resultado en un nuevo DataFrame llamado nuevo_df. El parámetro thresh especifica el umbral de valores no nulos necesarios para conservar una columna, y axis=1 indica que se deben eliminar columnas (en lugar de filas).
nuevo_df.info() # Proporciona información sobre el nuevo DataFrame nuevo_df, incluyendo el número de filas, columnas, tipos de datos y cantidad de valores no nulos en cada columna después de eliminar las columnas con más del 50% de valores nulos.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [13]:
df_no_nulos = nuevo_df.dropna(axis=0, subset=['age', 'embark_town', 'embarked'], how='any') # Elimina las filas del DataFrame nuevo_df que tengan valores nulos en la columna 'age' y guarda el resultado en un nuevo DataFrame llamado df_no_nulos. El parámetro axis=0 indica que se deben eliminar filas, y subset=['age'] especifica que solo se deben considerar los valores nulos en la columna 'age' para eliminar las filas.
df_no_nulos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     712 non-null    int64
 1   pclass       712 non-null    int64
 2   sex          712 non-null    object
 3   age          712 non-null    float64
 4   sibsp        712 non-null    int64
 5   parch        712 non-null    int64
 6   fare         712 non-null    float64
 7   embarked     712 non-null    object
 8   class        712 non-null    category
 9   who          712 non-null    object
 10  adult_male   712 non-null    bool
 11  embark_town  712 non-null    object
 12  alive        712 non-null    object
 13  alone        712 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 69.0+ KB